config/routes.rb
Rails.application.routes.draw do
  get 'users/favourites'
  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
      get "like", to: "posts#upvote"
    end
  end
  get 'tobe_posted', to: 'posts#tobe_posted'
  resources :replies
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  has_many :replies
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  has_many :comments, dependent: :destroy
  has_attached_file :image,
  storage: :fog,
  fog_credentials: {google_storage_access_key_id: 'GOOG6ZKIR4VVUBSI7Q2G',
    google_storage_secret_access_key: '3MLsKF8KFmv36MpfvbPYVYWl7z06PWEmCkfdr+jJ',
    provider: 'Google',
    path_style: true
    },
  fog_directory: "trail-1353.appspot.com"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_presence_of :name
  validates_uniqueness_of :name, case_sensitive: false
  validates_presence_of :year
  validates_presence_of :image
  extend FriendlyId
  friendly_id :name, use: :slugged

  def self.movie_name(movie_name)
    if movie_name
      self.where("lower(name) LIKE ?", "%#{movie_name}%".downcase)
    else
      self.all
    end
  end
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :comment
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_voter
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, 
  :omniauthable, :confirmable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.skip_confirmation!
      user.save!
    end
  end
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.update_attributes(username: "#{current_user.email}")
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.friendly.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :destroy]
  before_action :check_admin, only: [:edit, :destroy]
  def index
    @posts = Post.order(id: :ASC).paginate(page: params[:page], per_page: 30)
    @posts = @posts.movie_name(params[:movie_name]) if params[:movie_name].present?
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      unless current_user.admin?
        flash[:notice] = "Post will show up after admin approval"
      end
      redirect_to posts_path
    else
      render('new')
    end
  end

  def show
    @post = Post.friendly.find(params[:id])
  end

  def edit
    @post = Post.friendly.find(params[:id])
  end

  def update
    @post = Post.friendly.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to posts_path
    else
      render('edit')
    end
  end

  def upvote
    @post = Post.friendly.find(params[:id])
    @post.upvote_from current_user
    redirect_to post_path(@post)
  end

  def tobe_posted
    @posts = Post.where(review: [nil, ""]).paginate(page: params[:page], per_page: 50)
  end

  def destroy
    @post = Post.friendly.find(params[:id])
    @post.destroy
    flash[:notice] = "Post #{@post.name} has been deleted"
    redirect_to posts_path
  end

  private

  def check_admin
    if current_user.admin? == false
      render status: :forbidden, text: "Forbidden"
    end
  end

  def post_params
    params.require(:post).permit(:name, :year, :review, :image)
  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :authenticate_user!
  def new
  end

  def create
    comment = Comment.find(params[:reply][:comment_id])
    @reply = Reply.new(reply_params)
    if @reply.save
      @reply.update_attributes(author: "#{current_user.email}")
      comment.replies << @reply
    end
    redirect_to :back
  end

    def destroy
    @reply = Reply.find(params[:id])
    @reply.destroy
    redirect_to :back
  end

  private 

  def reply_params
    params.require(:reply).permit(:content, :comment_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def favourites
    @a = current_user.votes.up
    @fav_posts = []
    @a.each do |a|
      if Post.exists?("#{a.votable_id}")
        @fav_posts << Post.find("#{a.votable_id}")
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def error_messages_for(object)
    render(partial: 'application/error_messages', locals: {object: object})
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_error_messages.html.erb
<% if object && object.errors.size > 0 %>
  <div id="errorExplanation">
    <h3><%= pluralize(object.errors.size, "error") %> prohibited this record from being saved</h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1">
<head>
	<title>Science Fictionaly</title>
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>	
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>				
				<div class= "navbar-brand" id="heading-container">
					<p id="heading">Science Ficitionaly</p>
				</div>
			</div>						
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right">
					<% if user_signed_in? %>
						<% if current_user.admin == true %>
							<li>
								<%= link_to "View Unapproved Posts", tobe_posted_path, class: "link_colors" %>
							</li>
						<% end %>	
						<li>
							<%= link_to "View Favourites", users_favourites_path, class: "link_colors" %>
						</li>
						<li>
							<%= link_to "#{current_user.email}", edit_user_registration_path, class: "link_colors" %>
						</li>
						<li id="ghl">
							<%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "btn btn-danger" %>        
						</li>
					<% else %>
						<li>
							<%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Up'.html_safe, new_user_registration_path, class: "link_colors" %>
						</li>
						<li>
							<%= link_to '<span class="glyphicon glyphicon-user"></span> Sign Up via Facebook'.html_safe, user_omniauth_authorize_path(:facebook), class: "link_colors" %>
						</li>
						<li>
							<%= link_to '<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path, class: "link_colors" %>
						</li>
					<% end %>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container-fluid" id="body">
		<div class="row">
			<div class="col-xs-10" style="background: lavender">
				<center>
					<% flash.each do |name, msg| %>
					<%= content_tag :div, msg, :id => "flash_#{name}" %>
					<% end %> 
				</center>
				<%= yield %>
				<br/>
			</div>
			<div class="col-xs-2">
				<div class="affix">
					<br/><br/><br/><br/><br/><br/>Place<br/><br/><br/><br/>your<br/><br/><br/><br/>
					ads<br/><br/><br/><br/>here
				</div>
			</div>
		</div>
	</div>
</body>
</html>

app/views/posts/_post.html.erb
<div class="container-fluid">
	<% @posts.each_slice(6) do |(p1, p2, p3, p4, p5, p6)| %>
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-md-4">
			<% if !p1.nil? %>
			<% unless p1.review.blank? %>
			<center>				
				<% if p1.image_file_name != "Not Found" %>
					<%= image_tag p1.image.url.gsub("https", "http") %>
				<% else %>
					<%= image_tag("404.png") %>
				<% end %>
				<br/>
				<b><%= p1.name %></b><br/>
				<%= p1.year %>
				<%= link_to "Show", post_path(p1) %>
				<br/>
			</center>
			<% end %>
			<% end %>      
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<% if !p2.nil? %>
			<% unless p2.review.blank?%>
			<center>
				<% if p2.image_file_name != "Not Found" %>
					<%= image_tag p2.image.url.gsub("https", "http") %>
				<% else %>
					<%= image_tag("404.png") %>
				<% end %>
				<br/>
				<b><%= p2.name %></b><br/>
				<%= p2.year %>
				<%= link_to "Show", post_path(p2) %>
				<br/>
			</center>
			<% end %>
			<% end %>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<% if !p3.nil? %>
			<% unless p3.review.blank? %>
			<center>
				<% if p3.image_file_name != "Not Found" %>
					<%= image_tag p3.image.url.gsub("https", "http") %>
				<% else %>
					<%= image_tag("404.png") %>
				<% end %>
				<br/>
				<b><%= p3.name %></b><br/>
				<%= p3.year %>
				<%= link_to "Show", post_path(p3) %>
				<br/>
			</center>
			<% end %>
			<% end %>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<% if !p4.nil? %>
			<% unless p4.review.blank? %>
			<center>
				<% if p4.image_file_name != "Not Found" %>
					<%= image_tag p4.image.url.gsub("https", "http") %>
				<% else %>
					<%= image_tag("404.png") %>
				<% end %>
				<br/>
				<b><%= p4.name %></b><br/>
				<%= p4.year %>
				<%= link_to "Show", post_path(p4) %>
				<br/>
			</center>
			<% end %>
			<% end %>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<% if !p5.nil? %>
			<% unless p5.review.blank? %>
			<center>
				<% if p5.image_file_name != "Not Found" %>
					<%= image_tag p5.image.url.gsub("https", "http") %>
				<% else %>
					<%= image_tag("404.png") %>
				<% end %>
				<br/>
				<b><%= p5.name %></b><br/>
				<%= p5.year %>
				<%= link_to "Show", post_path(p5) %>
				<br/>
			</center>
			<% end %>
			<% end %>
		</div>
		<div class="col-xs-12 col-sm-6 col-md-4">
			<% if !p6.nil? %>
			<% unless p6.review.blank? %>
			<center>
				<% if p6.image_file_name != "Not Found" %>
					<%= image_tag p6.image.url.gsub("https", "http") %>
				<% else %>
					<%= image_tag("404.png") %>
				<% end %>
				<br/>
				<b><%= p6.name %></b><br/>
				<%= p6.year %>
				<%= link_to "Show", post_path(p6) %>
				<br/>
			</center>
			<% end %>
			<% end %>
		</div>
	</div>
	<% end %>
</div>

app/views/posts/_postform.html.erb
<div class="form-group">
  <%= f.label :name, "Add the name of the Movie:", class: "col-md-4 control-label" %>
  <div class="col-md-8">
    <%= f.text_field :name, placeholder: "Name", style: "width: 400px;"%><br />
  </div>
</div>
<div class="form-group">
  <%= f.label :year, "Year of Release", class: "col-md-4 control-label" %>
  <div class="col-md-8">
    <%= f.text_field :year, placeholder: "Year" %><br />
  </div>
</div>
<div class="form-group">
  <%= f.label :image, "Please add an Image file: ", class: "col-md-4 control-label" %>
  <div class="col-md-8">
    <%= f.file_field :image %>
  </div>
</div>

<% if current_user.admin? %>
<div class="form-group">
  <%= f.label :review, "Please write a Review: ", class: "col-md-4 control-label" %>
  <div class="col-md-8">
    <%= f.text_area :review, size: "50x6", placeholder: "Write a Review" %><br />
  </div>
</div>
<% end %>

app/views/posts/edit.html.erb
<center><%= error_messages_for(@post) %></center>

<%= form_for(@post, url: {action: 'update', id: @post.id}, html: { multipart: true, :class => "form-horizontal center" }) do |f| %>
  
  <%= render(partial: 'postform', locals: {f: f}) %>

  <center><%= f.submit "Update Post", class: "btn btn-success" %></center>

<% end %>
  

app/views/posts/index.html.erb
<div class="row" style="padding-bottom:10px;">
	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
		<center>
		<h3>Don't see what you are looking for?</h3>
		Add a new movie to our database. We absolutely encourage it !
		<span class="btn btn-success"><%= link_to "Add Post", new_post_path, {:style=>'color:#FFFFFF;'} %></span>
	</center>
	</div>
	<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
		<center>
			<br/>
			<%= form_tag('/posts', method: :get, enforce_utf8: false) do %>
			<%= text_field_tag :movie_name, params[:movie_name] %><br/>
			<%= submit_tag "Search Movie", name: nil, class: "btn btn-primary" %>
			<% end %>
		</center>
	</div>
</div>
<br/><br/>
<div id="posts">
	<%= render('post')	%>
</div>
<center>
	<div id="pag">
		<%= will_paginate @posts %>
	</div>
</center>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render('post') %>');
$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');

app/views/posts/new.html.erb
<center>
  <%= error_messages_for(@post) %>
  <h2> Add Details of the New Movie </h2>
</center><br/>
<%= form_for(:post, url: {action: 'create'}, html: { multipart: true, class: "form-horizontal center"}) do |f| %>

  <%= render(partial: 'postform', locals: {f: f}) %>
  
  <center>
    <%= f.submit "Save Post", class: "btn btn-primary" %>
  </center>

<% end %>

app/views/posts/show.html.erb
<center>
	<div id="namecontainer">
		<span id="post-name"><%= @post.name %></span><br/>
		<%= link_to "Edit", edit_post_path(@post) if user_signed_in? && current_user.admin? %>		
		<%= button_to 'Delete', post_path(@post), data: {confirm: 'Are you sure?'}, method: :delete, class: "del_post_button"  if user_signed_in? && current_user.admin? %>
		<br/>
	</div>
</center>
<div class="row">	
	<div class="col-sm-6 col-xs-12" id="imagecolumn">
		<div id="imgcontainer">
			<% if @post.image_file_name != "Not Found" %>
				<%= image_tag @post.image.url.gsub("https", "http") %>
			<% else %>
				<%= image_tag("404.png") %>
			<% end %>
		</div>
	</div>
	<div class="col-sm-6 col-xs-12" id="textcontainer">
		<div align="center">
			<span class="field">Year</span><%= @post.year %><br/>
			<span class="field"><%= @post.director %></span><br/><br/>
			<span id="review"><%= @post.review %></span><br/>
			<%= link_to like_post_path(@post), method: :put do %>
			<button type="button" class="btn btn-info">
				<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
				<span class="badge"><%=@post.get_upvotes.size %></span>
			</button>
			<br/>Mark Favourite
			<% end %>
		</div>
	</div>	
	&nbsp;
</div>
<br/>
<% if user_signed_in? %>  
<%= form_for([@post, @post.comments.build], html: {class: "form-inline"}) do |f| %>
<div class="form-group">
	<%= f.label :comment, "Leave a Comment", class: "col-xs-4 control-label" %>
	<div class="col-md-8">
		<%= f.text_area :name, size: "20*2" %>
	</div>
</div>
<%= f.submit "Comment", class: "btn btn-primary" %>
<% end %>
<% end %>
<br/>
<h3><i>Recent Comments</i></h3>
<hr/>
<% @post.comments.reverse.each do |comment| %>
<% if comment.persisted? %>
<span id="comment">
	<b><u><%= comment.username %></b></u>
	<div class="inlinecontentspacing" style="color: green;"><%= comment.name %></div>
</span>
<% if user_signed_in? %>
<% if current_user.email == comment.username || current_user.admin? %>
<span class="tabspace"><%= button_to 'Delete', [comment.post, comment],
confirm: 'Are you sure?',
method: :delete, class: "commentbtn" %></span>
<% end %>
<% end %>

<% comment.replies.each do |reply| %>
<br/>
<div id="reply">
	<div style="float: left; width: auto; text-indent: 3em;">
		<b><u><%= reply.author %></b></u>
		<div class="inlinecontentspacing" style="color: blue;"><%= reply.content %></div>
	</div>
	<% if user_signed_in? %>
	<% if current_user.email == reply.author || current_user.admin? %>
	<span class="tabspace"><%= button_to 'Delete', reply_path(reply),
	confirm: 'Are you sure?',
	method: :delete %></span>
	<% end %>
	<% else %>
	<br/><strong style="color:red;">Sign in to leave a reply or comment</strong>
	<% end %> 
</div>   
<% end %>

<br/>
<% if user_signed_in? %>
<%= form_for :reply, url: replies_path, html: {class: "form-inline"} do |f| %>
<%= f.hidden_field :comment_id, value: comment.id %>
<div class="form-group">
	<%= f.text_field :content, placeholder: "Reply" %>        
</div>
<%= f.submit "Reply", class: "btn btn-default" %>
<% end %>
<hr/>
<% end %>
<% end %>
<% end %>
<hr/>

app/views/posts/tobe_posted.html.erb
<% @posts.each do |post| %>
<br/>
<%= post.name %>
<%= link_to "Show", post_path(post) %>
<td><%= link_to "Edit", edit_post_path(post) %>
<br/>
<% end %>
<%= will_paginate @posts %>

app/views/users/favourites.html.erb
<div class="table-responsive">
	<table class="table table-hover">
		<tr>
			<th>Name</th>
			<th>Year</th>
			<th>Action</th>
		</tr>
		<% @fav_posts.each do |post| %>
			<tr>
				<td><%= post.name %></td>
				<td><%= post.year %></td>
				<td><%= link_to "Show", post_path(post) %>
			</tr>
		<% end %>
	</table>
</div>